### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [PhilsLab/abbr-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

**Comment by PhilsLab** [comment]
Thanks for being interested in doing that! I will definitely do that in the next few days.

**Comment by PhilsLab** [comment]
I finished the features I wanted to implement, and a screenshot has been added.

**Comment by unixorn** [comment]
Thanks! Adding as part of https://github.com/unixorn/awesome-zsh-plugins/pull/583
